spring.application.name=StockApp
server.address=0.0.0.0

# Usa variáveis de ambiente com fallback para desenvolvimento local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/stockapp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.javax.persistence.schema-generation.scripts.action=update
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=update.sql
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-source=metadata

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true